modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="mindustry"
displayName="mindustry"
credits=""
version="${file.jarVersion}" #managed by "build.gradle"
displayURL="https://???.net"
description='''
A Minecraft mod about the game 《Mindustry》
'''
logoFile="logo.png"
authors="shan_luan_,luobochuanqi"

[[dependencies.mindustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mindustry]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"