modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="mindustry"
version="0.2.1"
displayName="mindustry"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="shan_luan_"

[[dependencies.mindustry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.mindustry]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.7,)"
    ordering="NONE"
    side="BOTH"



