# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

on:  #触发条件
  push:
    branches: [ Fabric-1.20.1 ]
  pull_request:
    branches: [ Fabric-1.20.1 ]

jobs: #具体的任务
  build:
    runs-on: ubuntu-latest #执行的环境

    steps:
      - name: checkout repository
        uses: actions/checkout@v3 #拉取项目文件

      - name: Set up JDK 17 #配置java环境
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew  #更改脚本权限
        run: chmod +x gradlew

      - name: Build with Gradle  #开始打包 -x test 跳过测试
        run: ./gradlew build -x test

      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/